//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceResetServiceRequest : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceResetService";
        public override string RosMessageName => k_RosMessageName;

        // request
        public Std.StringMsg @params;

        public UniLaceResetServiceRequest()
        {
            this.@params = new Std.StringMsg();
        }

        public UniLaceResetServiceRequest(Std.StringMsg @params)
        {
            this.@params = @params;
        }

        public static UniLaceResetServiceRequest Deserialize(MessageDeserializer deserializer) => new UniLaceResetServiceRequest(deserializer);

        private UniLaceResetServiceRequest(MessageDeserializer deserializer)
        {
            this.@params = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@params);
        }

        public override string ToString()
        {
            return "UniLaceResetServiceRequest: " +
            "\n@params: " + @params.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
