//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceInfoServiceRequest : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceInfoService";
        public override string RosMessageName => k_RosMessageName;

        // request
        public Std.BoolMsg render;

        public UniLaceInfoServiceRequest()
        {
            this.render = new Std.BoolMsg();
        }

        public UniLaceInfoServiceRequest(Std.BoolMsg render)
        {
            this.render = render;
        }

        public static UniLaceInfoServiceRequest Deserialize(MessageDeserializer deserializer) => new UniLaceInfoServiceRequest(deserializer);

        private UniLaceInfoServiceRequest(MessageDeserializer deserializer)
        {
            this.render = Std.BoolMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.render);
        }

        public override string ToString()
        {
            return "UniLaceInfoServiceRequest: " +
            "\nrender: " + render.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
