//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceStepServiceRequest : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceStepService";
        public override string RosMessageName => k_RosMessageName;

        // request
        public Std.StringMsg act;

        public UniLaceStepServiceRequest()
        {
            this.act = new Std.StringMsg();
        }

        public UniLaceStepServiceRequest(Std.StringMsg act)
        {
            this.act = act;
        }

        public static UniLaceStepServiceRequest Deserialize(MessageDeserializer deserializer) => new UniLaceStepServiceRequest(deserializer);

        private UniLaceStepServiceRequest(MessageDeserializer deserializer)
        {
            this.act = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.act);
        }

        public override string ToString()
        {
            return "UniLaceStepServiceRequest: " +
            "\nact: " + act.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
