//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceStepServiceResponse : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceStepService";
        public override string RosMessageName => k_RosMessageName;

        // response
        public Std.StringMsg obs;
        public Std.UInt8MultiArrayMsg obs_raw;

        public UniLaceStepServiceResponse()
        {
            this.obs = new Std.StringMsg();
            this.obs_raw = new Std.UInt8MultiArrayMsg();
        }

        public UniLaceStepServiceResponse(Std.StringMsg obs, Std.UInt8MultiArrayMsg obs_raw)
        {
            this.obs = obs;
            this.obs_raw = obs_raw;
        }

        public static UniLaceStepServiceResponse Deserialize(MessageDeserializer deserializer) => new UniLaceStepServiceResponse(deserializer);

        private UniLaceStepServiceResponse(MessageDeserializer deserializer)
        {
            this.obs = Std.StringMsg.Deserialize(deserializer);
            this.obs_raw = Std.UInt8MultiArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.obs);
            serializer.Write(this.obs_raw);
        }

        public override string ToString()
        {
            return "UniLaceStepServiceResponse: " +
            "\nobs: " + obs.ToString() +
            "\nobs_raw: " + obs_raw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
