//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceParamServiceRequest : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceParamService";
        public override string RosMessageName => k_RosMessageName;

        // request

        public UniLaceParamServiceRequest()
        {
        }
        public static UniLaceParamServiceRequest Deserialize(MessageDeserializer deserializer) => new UniLaceParamServiceRequest(deserializer);

        private UniLaceParamServiceRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "UniLaceParamServiceRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
