//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceParamServiceResponse : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceParamService";
        public override string RosMessageName => k_RosMessageName;

        // response
        public Std.StringMsg params_json;

        public UniLaceParamServiceResponse()
        {
            this.params_json = new Std.StringMsg();
        }

        public UniLaceParamServiceResponse(Std.StringMsg params_json)
        {
            this.params_json = params_json;
        }

        public static UniLaceParamServiceResponse Deserialize(MessageDeserializer deserializer) => new UniLaceParamServiceResponse(deserializer);

        private UniLaceParamServiceResponse(MessageDeserializer deserializer)
        {
            this.params_json = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.params_json);
        }

        public override string ToString()
        {
            return "UniLaceParamServiceResponse: " +
            "\nparams_json: " + params_json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
