//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UniLace
{
    [Serializable]
    public class UniLaceInfoServiceResponse : Message
    {
        public const string k_RosMessageName = "uni_lace_msgs/UniLaceInfoService";
        public override string RosMessageName => k_RosMessageName;

        // response
        public Std.StringMsg info;

        public UniLaceInfoServiceResponse()
        {
            this.info = new Std.StringMsg();
        }

        public UniLaceInfoServiceResponse(Std.StringMsg info)
        {
            this.info = info;
        }

        public static UniLaceInfoServiceResponse Deserialize(MessageDeserializer deserializer) => new UniLaceInfoServiceResponse(deserializer);

        private UniLaceInfoServiceResponse(MessageDeserializer deserializer)
        {
            this.info = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info);
        }

        public override string ToString()
        {
            return "UniLaceInfoServiceResponse: " +
            "\ninfo: " + info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
